version: "3.7"
services:
  dev:
    build:
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - postgres
    volumes:
      - ../:/workspaces:cached
    ports:
      - 3070:3070
      - 3071:3071
      - 9229:9229

  # postgres:
  postgres:
    image: postgres:16-bookworm
    shm_size: 128mb
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpostgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ../.dev-data/postgres:/var/lib/postgresql/data

  # postgres management ui (old but works...)
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # required for faststream (could also use kafka, rabbitmq or nats)
  redis:
    image: redis:7.2-bookworm
    ports:
      - 6379:6379
    volumes:
      - ../.dev-data/redis:/data

  # qdrant:
  #   image: qdrant/qdrant
  #   ports:
  #     - 6333:6333
  #     - 6334:6334
  #   volumes:
  #     - ../.docker-data/qdrant-storage:/qdrant/storage:z

  # memgraph
  # memgraph-platform:
  #   image: memgraph/memgraph-platform
  #   ports:
  #     - "7687:7687"
  #     - "7444:7444"
  #     - "3000:3000"
  #   volumes:
  #     - "../.docker-data/memgraph-data:/usr/lib/memgraph/data"